### PR TITLE
Update examples to work on 0.15.1

### PR DESCRIPTION
**Pull request by fredcy**
This PR merges in https://github.com/johnpmayer/elm-webgl/pull/38 by @aforemny that was never merged into upstream. To get the examples to work I also had to modify the elm-package.json to use the local version of elm-webgl.  In this branch all the examples work OK in elm-reactor 0.15.1. I figure that updating to 0.16 can be done in another PR.

### CODE REVIEW

**Comment by fredcy** [comment]
The bit where examples/elm-package.json uses "../src" to get the WebGL module confuses me a bit. It seems right that examples code would refer to the code that it's bundled with, to make it self-standing. Otherwise, how can changes that have to be coordinated between the main module and the test code ever be done without kludging in elm-stuff?

**Comment by mgold** [comment]
I think that's exactly what `..` does. The tests rely on the local source, not the published source. The code under test is not a third party lib; it's just more source code.

See [here](https://github.com/mgold/elm-nonempty-list/blob/master/test/elm-package.json) for another example. While I'd prefer a dev-dependencies field like in npm, having this separate package file works.

**Comment by fredcy** [comment]
Right. I added "../src" and removed the dependency on the published version for just that reason. I'm just puzzled about why it was like that in the first place.

**Comment by mgold** [comment]
Oh - maybe because John didn't know about it? Anyway, it's fixed now.

**Comment by mgold** [comment]
Now for the 0.16 update...

**Pull request merged**
